version: '3.3'
services:
  backend:
    build: .
    ports:
      - $BACKEND_PORT:3000
    volumes:
      - .:/backend

    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    volumes:
      - .dbdata:/var/lib/mysql

